services:
  - type: web
    name: curbonomix-backend
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CORS_ALLOW_ORIGIN
        value: "*"   # set to your frontend origin in production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
    disk:
      name: storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
